### ISSUE TITLE
Generate namespace app\Models;

### ISSUE THREAD

**Issue by ojisatriani** [arwahyu01/mvc-builder#1]
Generate namespace is "app\Models", dafault laravel is "App\Models".
if you call Model in controller or other, got error namespace "app\Models" Not Found.

**Comment by arwahyu01** [comment]
Tanks for the advice, i'll fix it soon

Pada tanggal Sen, 28 Agu 2023 19.47, Oji Satriani ***@***.***>
menulis:

**Comment by arwahyu01** [comment]
> Generate namespace is "app\Models", dafault laravel is "App\Models". if you call Model in controller or other, got error namespace "app\Models" Not Found.

Please update your composer.json; I fixed it.
