### ISSUE TITLE
Case Sensitive Factory Relationship

### ISSUE THREAD

**Issue by ojisatriani** [arwahyu01/mvc-builder#2]
Laravel documentation https://laravel.com/docs/10.x/eloquent-factories#factory-relationships
`['belongsTo', 'hasMany', 'hasOne', 'belongsToMany']`
not
`['BelongsTo', 'HasMany', 'HasOne', 'BelongsToMany']`

**Comment by arwahyu01** [comment]
Thank you for the information, I have incorporated this in the latest release.

> Laravel documentation https://laravel.com/docs/10.x/eloquent-factories#factory-relationships `['belongsTo', 'hasMany', 'hasOne', 'belongsToMany']` not `['BelongsTo', 'HasMany', 'HasOne', 'BelongsToMany']`
